---
output: 
  html_document: 
    number_sections: yes
---

# 可选题目
## 

## 



# realized-garch模型
**选题想法**

- 深港通开通前后波动率分析和相关性研究（高频数据Realized GARCH Copula 模型构建）
- 高频数据Realized GARCH Copula  模型构建和相关性研究——基于深港通和沪港通

数据可从wind数据库获取
2016年12月5日，深港通正式启动，2014年开通沪港通。探究深港通启动前后深港股市的相
关结构是否有变化。文献使用的数据时间都比较短和旧，可以将时序拉长进行对比分析，考虑到收益率的均值回复与长记忆性特性，在Realized GARCH模型基础上，构建ARFIMA-Realized GARCH模型。


**选题文献**


1. 高频数据Realized GARCH Copula模型构建及相关性测度_苏新星

针对金融市场多变量时间序列之间的相关性，以Realized GARCH 模型为边缘分布，选取经典的t-Copula函数建立Realized GARCH Copula模型，度量深圳和香港两金融市场之间的相关
性，对比纳入不同的已实现测度的度量效果.
本文通过改进的模型及比对纳入不同的己实现测度时的实证效果，提高波动
率预测的准确性和ＶａＲ度量风险的精度，更好地进行风险管理；通过对深圳和
香港两金融市场的相关性度量，对深港通启动后两金融市场的相关性后续研究有
参考作用，同时对投资组合、市场风险管理等也有着应用价值和参考价值。

在实证上，以理论指导为前提，采用了深证成指和恒生指数的高频数据进行
实证研宄，借助Ｒ软件分析数据，首先对推广后的Realized GARCH模型与传统
GARCH类模型进行实证对比，其次纳入不同的己实现测度，并在各模型下进行实证研究分析，比较在不同的已实现测度选择下各组模型的实证效果。在回测方法上，除VaR检验外，针对具体问题，还引入的Kupic经验失败率检验法和基于风险管理视角的损失函数。最后纳入不同的己实现测度Realized GARCH Copula模型对深证成指和恒生指数的相关性进行测度，实证对比度量效果。

2. 基于Copula函数的深港通开通前后沪港股市相关性分析

以上证指数和恒生指数作为研究对象，通过构建 t-Copula 模型对深港通开通前后沪港股市的相 关性进行分析，研究发现，沪港两地股票市场的在深港通开通前后都存在着正项相关关系，但相关系数不大，在 深港通开通之后，沪港两地股市的相关性有所降低。一方面说明深港通的开通资金流向出现一定程度的分流 现象，致使沪股和港股市的相关程度降低，同时也说明深港通开通的有效性。 

深港通于 2016 年 12 月 5 日正式开通，文中 选取深港通开通前 30 个交易日的上证指数
和香 港恒生指数数据以及深港通开通后的上证指数和 香港恒生指数数据，即选取 2016 年
10 月 24 至 2016 年12 月 31 日上证指数和香港恒生指数的 收盘价价格( 由于交易时间
的不同，保障数据的 同步性，剔除日期不一致数据) 。

3. 利用已实现极差预测市场波动率 ——基于ARFIMA-Realized GARCH模型的实证研究

考虑到收益率的均值回复与长记忆性特性，在Realized GARCH模型基础上，提出了
ARFIMA-Realized GARCH模型。综合日内已实现极差，以沪深300指数为样本对市场波动率进
行了预测，并采 用MCS检验法对预测结果进行比较。实证结果发现，在波动率预测上，考虑
了收益率长记忆性的ARFIMA-Realized GARCH模型要优于未考虑收益率长记忆性的Realized
GARCH模型；采用能够克服市场微观 结构偏差影响的已实现极差作为已实现测度，很大程度
上改进了模型的预测效果；与已实现波动率相比， 已实现极差可以适用于包含更多信息的
更高频率的数据集并能有效提高预测效果

沪深300指数自2005 年推出以来已经12年，涵盖了沪深两市不同行业 的龙头企业。本文采用的样本为2010年1月4日至 2016年12月15日共1689个交易日的高频数据。选 取5min及1min高频数据对波动率进行预测。 