---
title: "笔记"
author: "SXM"
date: "2020年3月"
institute: 中南财经政法大学统计与数学学院
csl: ./style/chinese-gb7714-2005-numeric.csl
css: ./style/markdown.css
bibliography: [./Bibfile.bib]
eqnPrefixTemplate: ($$i$$)
link-citations: true
linkReferences: true
chapters: true
tableEqns: false
autoEqnLabels: false
classoption: "aspectratio=1610"
---



# 资料整理
## 刊物
1. 统计研究（1.912）
   http://navi.cnki.net/KNavi/JournalDetail?pcode=CJFD&pykm=TJYJ 
2. 统计与决策(0.638)
   http://navi.cnki.net/KNavi/JournalDetail?pcode=CJFD&pykm=TJJC
3. 时代金融(0.051)
   http://navi.cnki.net/KNavi/JournalDetail?pcode=CJFD&pykm=YNJR
4. 国际金融研究(2.831)
   http://navi.cnki.net/KNavi/JournalDetail?pcode=CJFD&pykm=GJJR
5. 国际金融(0.615)
   http://navi.cnki.net/KNavi/JournalDetail?pcode=CJFD&pykm=JRGJ
6. 南方金融(1.391)
   http://navi.cnki.net/KNavi/JournalDetail?pcode=CJFD&pykm=GDJR 
7. 数量经济技术经济研究(3.165)
   http://navi.cnki.net/KNavi/JournalDetail?pcode=CJFD&pykm=SLJY
8. Econometrics and Statistics
9. Journal of Econometrics
10. International Journal for Theoretical and Applied Statistics

## 统计部分模型整理：
1. 常用的金融风险的模型：波动性方法、VaR模型、灵敏度分析法、一致性风险度量模型、
   CVaR模型（Condition Value at Risk）条件风险价值（CVaR）模型、条件风险价值
   （CVaR）模型、条件风险价值（CVaR）模型、谱风险测度(但是该测度实际计算的难度很
   大，维数过高时，即使转化成线性规划问题，计算也相当困难。)、信息熵方法
2. 混频GARCH-MIDAS模型:宏观，经济不确定新，混频数据
3. KMV模型是现代信用风险度量的重要模型(KMV模型衍生于期权定价理论,利用股权价值、
   股权价值波动率、企业违约点推算企业资产价值和资产价值的波动率,从而求出违约距
   离,并得出企业预期违约率)
4. DCC-GARCH模型对股债两市场间的动态相关性建模,并对动态相关系数的时变性和趋势进
   行探讨分析，VECM模型估计长期均衡方程,对估计结果进行深层次的原因分析。在实证层
   面,先运用DCC-GARCH模型对股债两市场间的动态相关性建模,并对动态相关系数的时变性
   和趋势进行探讨分析。

# 可选题目
## 股市波动率分析和相关性研究
### 选题文献
1. **高频数据Realized GARCH Copula模型构建及相关性测度_苏新星**

如何将GARCH类模型框架与纳入高频数据信息的已实现测度相结合成为了国内外学者研究波
动率建模的一个热门研究方向。该模型是Hansen等在2012年提出的基于GARCH模型引入已实
现测度ＲＶ所构建的模型通过测量方程将己实现测度和GARCH模型的条件波动率相联系起
来，并对其进行了实证研究分析，结果表明了相较于传统的GARCH类模型其能够提高了对波
动预测的能力，因而该模型得到了广泛的认可和研究应用。

Ａｎｄｅｒｓｎ和Ｂｏｌｌｅｒｓｌｅｖ（1998）首次提出了纳入高频数据信息的已实现波
动RV（Realized Volatility,RV），用５分钟高频采样的数据来计算已实现波动ＲＶ并得出
如下结论，即采用５分钟高频数据对真实波动进行估计能够使精确率和金融市场微观结构噪
声达到最佳的平衡。

采用ｔ分布作为残差分布的realized-garch模型，使用四种不同高频数据己实现波动测度比
较了其VaR预测效果。研究金融市场的相关性，研究学者们常用的为Copula方法体系
sklar(1959）最早提出Copula理论，由于Copula函数具有不受边缘分布的限制，并能够准确
反映各变量间的相关模型，处理变量之间的非线性、非对称性和尾部相关等问题等优势，
Copula函数成为了金融市场中金融时间序列间相关性结构建模的标准化工具，从而它的理论
及应用研究得到了研究学者们的广泛关注。Realized GARCH模型与Copula函数相结合的相关
模型在2013年才被提出，相关研究较少。

针对金融市场多变量时间序列之间的相关性，以Realized GARCH 模型为边缘分布，选取经
典的t-Copula函数建立Realized GARCH Copula模型，度量深圳和香港两金融市场之间的相
关性，对比纳入不同的已实现测度的度量效果.本文通过改进的模型及比对纳入不同的己实
现测度时的实证效果，提高波动率预测的准确性和ＶａＲ度量风险的精度，更好地进行风险
管理；通过对深圳和香港两金融市场的相关性度量，对深港通启动后两金融市场的相关性后
续研究有参考作用，同时对投资组合、市场风险管理等也有着应用价值和参考价值。

在实证上，以理论指导为前提，采用了深证成指和恒生指数的高频数据进行实证研宄，借助
Ｒ软件分析数据，首先对推广后的Realized GARCH模型与传统GARCH类模型进行实证对比，
其次纳入不同的己实现测度，并在各模型下进行实证研究分析，比较在不同的已实现测度选
择下各组模型的实证效果。在回测方法上，除VaR检验外，针对具体问题，还引入的Kupic经
验失败率检验法和基于风险管理视角的损失函数。最后纳入不同的己实现测度Realized
GARCH Copula模型对深证成指和恒生指数的相关性进行测度，实证对比度量效果。高频数据
Realized_GARCH_Copula模型构建及相关性测度

金融时间序列的波动率和相关性是风险管理、资产组合和资产配置的基础。

选取深证成指和恒生指数作为实证数据，缺乏全面性，后期可考虑对期货、股指期货、汇率
和其他股市指数等进行基于Realized GARCH Copula 模型的资产组合、资产配置和风险管理
的研究，从而证明该模型的适用性。本文仅以t-Copula函数来拟合深港股市的静态相关结
构，并考虑其动态相关结构和是否存在非线性相关关系，后续的研宄可以尝试将其他类的
Copula函数。随着对己实现测度的研宄的发展，涌现了大量的创新的己实现测度，后续研究
可以尝试纳入其他已实现测度进行研究

2. **基于Copula函数的深港通开通前后沪港股市相关性分析**
   
   以上证指数和恒生指数作为研究对象，通过构建 t-Copula 模型对深港通开通前后沪港
   股市的相 关性进行分析，研
   究发现，沪港两地股票市场的在深港通开通前后都存在着正项相关关系，但相关系数不
   大，在 深港通开通之后，沪港两地股市的相关性有所降低。一方面说明深港通的开通资
   金流向出现一定程度的分流 现象，致使沪股和港股市的相关程度降低，同时也说明深港
   通开通的有效性。 

深港通于 2016 年 12 月 5 日正式开通，文中 选取深港通开通前 30 个交易日的上证指数
和香 港恒生指数数据以及深港通开通后的上证指数和 香港恒生指数数据，即选取 2016 年
10 月 24 至 2016 年12 月 31 日上证指数和香港恒生指数的 收盘价价格( 由于交易时间
的不同，保障数据的 同步性，剔除日期不一致数据) 。

3. **利用已实现极差预测市场波动率 ——基于ARFIMA-Realized GARCH模型的实证研究**
   考虑到收益率的均值回复与长记忆性特性，在Realized GARCH模型基础上，提出了
   ARFIMA-Realized GARCH模型。综合日内已实现极差，以沪深300指数为样本对市场波动
   率进行了预测，并采 用MCS检验法对预测结果进行比较。实证结果发现，在波动率预测
   上，考虑了收益率长记忆性的ARFIMA-Realized GARCH模型要优于未考虑收益率长记忆性
   的Realized GARCH模型；采用能够克服市场微观结构偏差影响的已实现极差作为已实现
   测度，很大程度上改进了模型的预测效果；与已实现波动率相比，已实现极差可以适用
   于包含更多信息的更高频率的数据集并能有效提高预测效果

沪深300指数自2005年推出以来已经12年，涵盖了沪深两市不同行业 的龙头企业。本文采用
的样本为2010年1月4日至 2016年12月15日共1689个交易日的高频数据。选取5min及1min高
频数据对波动率进行预测。 

### 题目
- 深港通开通前后波动率分析和相关性研究（高频数据Realized GARCH Copula 模型构建）
- 高频数据Realized GARCH Copula  模型构建和相关性研究——基于深港通和沪港通

### 想法
数据可从wind数据库等获取上证综指、深证成指和恒生指数。2016年12月5日，深港通正式启
动，2014年开通沪港通。探究深港通启动前后深港股市的相关结构是否有变化。文献使用的数
据时间都比较短和旧，可以将时序拉长进行对比分析，考虑到收益率的均值回复与长记忆性
特性，在Realized GARCH模型基础上，构建ARFIMA-Realized GARCH模型。



## 系统性风险研究
### 选题文献
1. **基于Copula_CoVaR方法的中美证券市场系统性风险研究_王文静**

本文利用了时变t-Copula函数模型对两个国家各行业
对股票市场的影响进行了建模利用极大似然方法估计所有的参数其次利用拟
合的t-Copula函数计算covar,系统性风险贡献.

本文主要选取了美国标普指数及其各行业指数及中国沪深指数与
沪深行业指数作为中美证券市场代表利用模型对
证券市场的系统性风险进行了分析讨论


采用了复合模型，用模型拟合函数的边缘分布，并用更适合实际金融数据特征且考虑时变
相依性的时变来拟合指数收益率数据最终用计算得到对股票市场各行业对整体股票
市场的系统性风险的影响进行研究。

对于股票市场内部的各组成部分对于股票市场整体系统性风险影响的研究
并不多，而且几乎没有人对于中美两国行业对于股票市场的影响做过对比分析


2. **基于动态 Copula-CoVaR系统性风险的评估**

近年来，CoVaR 模型是近年来 衡量系统性风险的主流方法。现有的研究 方法只关注了静态
情形而忽略了动态情 形，文章在 Copula 框架下考虑了 DCCGARCH 模型下的动态
Copula-CoVaR 模型和广义自回归得分（GAS）模型下的 动态 Copula-CoVaR 模型，并对
CoVaR 进行了再次定义。 在应用方面选取上证 指数中具有代表性的 6 家金融机构从
2014~2016 年的股票数据，对选取的数据 进行系统性风险评估。 通过上述方法可 以筛选
出高危的金融机构， 对金融风险 防范工作具有一定的指导意义和参考价 值。 

通过已有的研究发现，大多数的研究 集中在传统的静态模型上，并且在研究视 角上大多集
中在金融系统之间的系统性 风险溢出效应， 忽略了子金融市场对金 融系统的风险溢出效
应的研究，在技术 手段上，已有的研究大多采用分位数回 归技术对 CoVaR 进行计算， 而
忽略了 GARCH 残差项分布对最终计算结果带 来的影响。 在此基础上，本文对CoVaR 模型
进行了拓展，引入了对金融系统与 子 金 融 机 构 相 关 关 系 描 述 性更 强 的Copula
函数， 对选取的具有代表性的 6 家子金融机构， 利用动态时变Copula CoVaR 模型，结合
金融系统进行系统性 风险的评估。

研究表明金融机构之间的相关关系 是随时间变化而变化的，尤其在经济低迷 时期,金融机
构之间的相关关系将变得更 强，此时若继续采用传统的静态方法进行 系统性风险评估将会
带来有偏，甚至无效 的结果，为此本文在接下来的研究中将上 述 方 法 推 广 到 了 动
态 条 件 相 关 系 数 GARCH 模型(Dynamic Conditional Correlation-GARCH， 即
DCC-GARCH 模 型) 和广义自回归得分模型(Generalized Autoregressive Score，简记为
GAS 模型)两 种动态模型。 


### 题目
- 中美股票市场系统性风险对比研究——基于动态 Copula-CoVaR

### 想法
- 美股在疫情期间多次熔断，十分动荡，可以与中国股市进行对比研究。
- 中美股票市场系统性风险：疫情期间，中美贸易摩擦，次贷危机极端金融事件
- 金融行业（银行证券，保险、信托），能源行业
- 分析中美两国股票市场系统性风险，不同行业对股票市场的系统性风险溢出效应差异，
- 通过差异对比，为我国股票市场预防行业风险提出建议。

# 确定主题
## 基于realized garch模型
[1]  Multivariate leverage effects and realized semicovariance GARCH models[J]. Journal of
Econometrics,2020(prepublish) [@Tim2020]. 

**文章内容**：

题目：多元杠杆效应和已实现半协方差模型

这篇文章提出了一种新的非对称多元波动率模型，提出了新的方法来捕获方差，协方差和收
益相关性的不对称响应。利用了方差和协方差的估计值，这些估计值考虑了高频收益的迹
象，称为**已实现的半方差，半协方差和半相关的度量**，与传统的二进制阈值相比，它们
对**正负收益冲击**具有更精细的响应基于程序。发现了迄今为止文献中所分析的模型所没
有解决的新的和有趣的动态依赖关系和对称的新响应。 

**提出的背景**：

由高频数据构成的已实现的波动性度量已被纳入更传统的GARCH类型的日和低频返回波动率
模型中，以提高模型的信息效率。Hansen等人的单变量和多变量realized -GARCH模型均未
包含非对称响应项，Hansen等人的单变量和多变量实现GARCH模型确实允许“杠杆效应”，但
这种效应仅在传统的阈值意义上，即波动性可能对每日的正负收益或更长期的创新产生不同
的反应。在这种背景下，提出了一类新的多元realized GARCH模型（multivariate
realized GARCH models），其中非对称性不取决于日收益率的符号，而是取决于日内收益
率的符号(intradaily returns)。

**数据**：

包含24种美国股票的高频日内数据以及S＆P500总体市场指数。为说明新方法的有效性，我
们考虑了24种股票和市场指数的双变量模型以及所有股票的24维联合模型。我们选择依赖相
对简单且广泛使用的双变量标量模型和DCC类型公式。

code and data
(https://www.econometricsociety.org/content/supplement-realized-semicovariances)

- 数据
  
本文大部分内容依赖于获得的S＆P500股票的高频回报数据从交易和报价（TAQ）数据库中获
取。 我们结论中的最终依据是从证券价格研究中心（CRSP）数据库获得的每日股票收益。
在不违反条款的前提下，本文中使用的原始数据无法公开获得明确禁止自由共享数据。

因此，我们以这样的方式设置了复制文件夹：访问这些数据库可以简单地以适当的格式粘贴
数据，然后复制只需按一个按钮即可打印纸。 要求的格式在相应的子文件夹Data/TAQ/
和Data/CRSP/

Data/文件夹包含我们分析中使用的公司列表，作为PERMNO的列表TAQ和CRSP数据库的编
号。 对于TAQ数据库，有三个与论文的不同部分相对应的不同列表。

- code
  
本文中所有结果均使用Ox 7.0开发。 该代码是独立的，除了由Peter Reinhard Hansen和
Asger开发的免费MulCom 3.0软件包Lunde，用于在补充附录中计算模型置信度集。

该代码分为两个文件。 首先，BLPQ2020 Replication.ox包含所有主要功能直接对数据进行
分析。 第二个，Helper.ox包含一个支持功能的集合。

BLPQ2020 Replication.ox文件的执行会复制整个纸张，并存储结果文件夹中的表格和数
字。 它的main（）函数运行整个复制。 它首先执行JCSD和DCSD测试，以及各种预测程序。
这些都存储在本地的结果，ForecastLoss和TVP文件夹中。 这些结果是由在main（）函数末
尾调用的一组函数使用，每个函数都直接与主要论文或补充附录中的图或表。

其他信息可以通过与作者联系获得。

**创新点**：

1. 新模型拟合的改进可能直接归因于数据中存在更复杂的动态依存关系和不对称性，这超
   出了传统基于阈值的不对称波动率模型所说明的那些。
2. 使用已实现的半方差，半协方差和半相关性可以使新模型适应“连续”而不是“阈值”不对
   称效应。现有的大多数非对称日波动率模型都根据其符号将其归类为“好”或“差”，并确
   定阈值类型。

**文章结构**

* 第二节：已实现的半协方差和多元波动率建模
* 第三节：数据描述
* 第四节：双变量波动率模型
* 第五节：高维多元波动率模型
* 结论：这种方法自然弥合了目前在多元波动率文献中存在的模型之间的不足：允许对正收
  益率和负收益率（通常称为“杠杆效应”）进行不对称反应的模型，以及那些采用高频数据
  和已实现波动率方法的模型（通常称为“已实现模型”）。

**难点**

1. 文章只有理论公式，实证只给出结论，有作者提供的ox文件，找不到包去实现
2. 这是一种新的模型，找不到其他realized semicovariance GARCH models文献


疑问：

1. '杠杆效应'
   金融市场对正和负新闻的反应不同。特别是，在负收益率之后，波动率会比等额正值冲
   击后增加更多（称为不对称性）。现在杠杆效应通常用于指代单变量和多变量的任何波
   动率模型，其中（协）方差对正向和负向冲击非对称地响应。
2. 传统的允许杠杆效应的garch模型  
3. 双变量模型以及所有股票的24维联合模型，DCC类型公式
4. 







# 参考文献
[//]: # (\bibliography{Bibfile})