---
title: "笔记"
author: "SXM"
date: "2020年3月"
institute: 中南财经政法大学统计与数学学院
csl: ./style/chinese-gb7714-2005-numeric.csl
css: ./style/markdown.css
bibliography: [./Bibfile.bib]
eqnPrefixTemplate: ($$i$$)
link-citations: true
linkReferences: true
chapters: true
tableEqns: false
autoEqnLabels: false
classoption: "aspectratio=1610"
---



# 选题文献
## Realized GARCH
1. Realising the future: Forecasting with high frequency based volatility
   (HEAVY) models [@Shephard2010]

**题目：** 预测未来：基于高频的波动率（heavy）模型进行预测(JOURNAL OF APPLIED
ECONOMETRICS,2010)

摘要：本文详细研究了一类基于**高频的波动率（HEAVY）模型**。 这些模型是
**基于高频数据构造的已实现测度的每日资产收益率波动的直接模型**。 
我们的分析表明，这些模型具有**动量效应和均值回归效应**，
并且可以**快速适应波动过程水平的结构性突破**。 我们研究了
**如何估算模型以及它们在信贷紧缩中的表现**，并将其拟合值与
更传统的GARCH模型进行了**比较**。 我
们分析了基于模型的引导程序，该引导程序使我们能够估算收益的整体预测分布。 我们还
将在这些模型的背景下提供缺失数据的分析。

**模型：**  高频波动率（HEAVY）模型，
旨在利用高频数据对收益波动率进行**多步预测**。

**文章结构**：第2节.我们将定义HEAVY模型，**该模型使用已实现的度量作为多周期提前预测波动率的基础**。 
我们将对这些模型进行详细分析。 在第3节中，我们详细介绍了整篇文
章中使用的“牛津大学学院的已实现图书馆”的主要属性。 在第4节中，我们将HEAVY模型拟
合到数据中，并将其预测与GARCH流程中的预测进行比较。 第5节讨论了可能的扩展。 第六
部分得出一些结论。

（动态效应：均值回归效应：市场微观结构噪声）

2. Realized GARCH:A joint model of returns and realized measures of
   volatility[@Hansen2012]

**题目**：已实现GARCH：收益率和已实现的波动率度量的联合模型（2012）

**首次提出已实现的GARCH，用于收益率的联合建模和已实现的波动率度量。**
**一个关键特征是将已实现的度量值与收益率的条件方差相关联的测量方程。** 
衡量方程式**有助于对收益与未来波动率之间的相关性进行简单建模**。 
具有线性或对数线性指定的已实现GARCH模
型具有许多吸引人的特征。 它们是简约的，易于估计，并且暗含着用于条件方差和已实现
度量的ARMA结构。 道琼斯工业平均指数股票和交易所交易指数基金的经验应用表明，与仅
使用每日收益的标准GARCH模型相比，简单的已实现GARCH结构可显著改善经验拟合。

## Realized wishart-garch
### 提出该模型的文献
Realized wishart-garch: A score-driven multi-asset volatility model [@Hansen2016a]

链接：https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2821497

**题目：**已实现的Wishart-GARCH：基于得分的多资产波动率模型

**摘要：**我们提出了一种新颖的多元GARCH模型，该模型结合了收益方差矩阵的已实现度
量。 关键的新颖之处在于，针对收益，实现的方差和实现的协方差的外部产品的多元动态
模型的联合制定。 方差矩阵的更新依赖于基于高斯和Wishart密度的联合似然函数的得分函
数。 动态模型是简约的，而每个创新仍然会影响方差矩阵的所有元素。 提供了基于不同小
样本量的参数估计的蒙特卡洛证据。 我们通过对15种美国金融资产组合的经验应用来说明
该模型。

高频数据；多元GARCH; 多元波动; 已实现的协方差；得分；Wishart密度。

**数据：**对股票的投资组合进行研究，股票由15个**道琼斯工业平均指数**组成，股票代
码为AA，AXP，BA，CAT，GE，HD，HON，IBM，JPM，KO，MCD，PFE，PG，WMT和XOM。 

**结论：**我们为金融资产的协方差矩阵的每日时间序列建模和预测提出了一个新模型：
Wishart-GARCH模型。挑战在于捕获资产方差和协方差之间复杂的时间相互依赖性。与替代
框架相比，我们的模型有两个与众不同的特征。首先，该模型既依赖于低频（每日）信息，
也依赖于高频（日内）信息。事实证明，鉴于高频度量利用金融资产的当日数据来推断当前
的协方差水平，因此权重最大。可以采用几种当前协方差水平的噪声和频率变化量度。
Wishart-GARCH模型的第二个特点是，**驱动协方差矩阵更新的创新利用了全部似然信息。**
因此，即使是简化的标量规格，也可以使所有资产的方差和协方差之间具有复杂的相互依
赖性。因此，该模型可以在不损失灵活性简约公式的情况下获得，这对于多元波动率模型是
方便的。在一项针对15个纽约证券交易所股票投资组合的实证研究中，我们将
Wishart-GARCH模型与其他多元GARCH模型以及指数加权移动平均方案进行了比较。我们模型
的样本拟合在比较中占主导地位。该发现不仅适用于股票的不同子集，还适用于全部股票投
资组合。与标准多元GARCH相比，该模型能够以更有效的方式跟踪资产的波动性和依赖结构
的突然变化。

**补充：**

1. Realized wishart-garch 可以看作是Realized GARCH模型在多变量情况下的扩展，但是
   它是新颖的，因为我们对**时变条件方差矩阵采用了分数驱动方法**。
2. 我们的主要目的是为每日时变方差矩阵指定一个模型，并通过使用低频和高频数据来提取该模型。
3. 采用分数驱动框架 [@Creal2013Generalized]加权方差和协方差矩阵。
4. 联合建模框架依赖于Wishart密度来实现已实现方差矩阵，并依赖于高斯密度来实现日收益向量。
5. 时变方差矩阵的更新由预测联合似然函数的标定分数驱动。分数函数证明是日收益的外
   部乘积与实际已实现度量的加权组合。加权取决于Wishart分布中的自由度数。我们将结
   果模型称为Wishart-GARCH模型。
6. 已实现度量是利用日内高频数据对方差矩阵进行更准确的度量
7. 在计算已实现的度量时，通常会排除隔夜收益，而对日收益的建模则基于开盘价和收盘价。
8. 对于单变量资产，wishart简化为伽马分布
9. 研究了不同样本大小T和资产数量k的估计性能。
10. 股票的投资组合有道琼斯15个**不同行业的公司**组成，在构造已实现的内核之前，我
    们对原始交易数据执行清理程序。 对逐笔数据进行清理，清理程序参考
    Barndorff-Nielsen 提供的清理程序 [@Barndorff-Nielsen2009]
    - 删除9:30 am4:00pm窗口之外带有时间戳的条目
    - 删除交易价格等于零的条目
    - 保留单个交易所条目
    - 删除交易更正条目
    - 删除销售条件异常的条目
    - 将中位数价格用于带有相同时间戳的多个交易
    - 我们删除价格高于要价加买卖价差的条目。
11. 在进行估计前，对于非同步交易，需要进行 Hayashi和Yoshida（2005) [@HayashiOn]
    以及 Voev和Lunde（2007） [@LundeIntegrated]提出的刷新时间抽样。
12. 选用BEKK,EWMA （指数加权移动平均）模型进行预测效果对比,使用两个损失函数来评
    估Wishart-GARCH模型相对于BEKK和EWMA的性能。
13. 与标准多元GARCH相比，该模型能够以更有效的方式跟踪资产的波动性和依赖结构的突然变化。

### 该模型实证应用-银行业
得分驱动的已实现Wishart-GARCH模型及应用(华科，统计与决策，2019)[@周少甫2019]

**摘要**文章以银行业为例，基于股票逐笔交易数据，在得分驱动的已实现Wishart-GARCH
模型的框架下， 对银行业规模靠前的多只个股对数收益率的已实现协方差矩阵尝试*多种降
噪方法*来进行建模以及预测，并检验预测效果。结果显示：
**该模型对于银行业个股间收益率的已实现协方差矩阵有着优于以往模型的良好预测效果。** 

**要点：**

已实现协方差；Wishart分布；GARCH模型；高频数据 

**已实现波动率**是基于日内收益计算的一种收益率，当基于的数据频率足够高 时，它是
对波动率的自然测度。由于已实现波动率的估计一般基于日内高频数据，因此其包含了更多
的市场信息， 相比低频数据而言更具有研究价值。

近年来关于已实现 波动率的研究越来越多，主要围绕已实现波动率的估计、 降噪方法以及
其与传统GARCH模型的结合展开。对于已实现波动率的建模需要克服两个主要问题：第一是
**如何在估计波动率时降噪**，第二个是**如何构建波动率模型。**除选择较低频数据的减
少噪声干扰外，还有3种方法：已实现核估计、子抽样已实现估计和子抽样已实现核估计
(Barndorff-Nielsen等（2011)证明不实用。

Gorg等[@Hansen2016a]提出了一种新的得分驱动的已实现Wishart-GARCH模型来**对多个资
产收益率构成的已实现协方差矩阵进行建模以及预测**。该模型是一个**多资产波动率模型
**，它将已实现波动率和Wishart-GARCH模型相结合，通过引入测度方程连接条件方差和已
实现波动率，并以得分驱动的方式来构建时变参数，其在预测多个资产收益率的已实现协方
差矩阵时效果远好于广义自回归得分模型(即得分驱动模型)。(两种模型效果可做对比)。将
新的模型应用于我国股市的单个行业内，由于我国股市单个行业内的关联性较强，因此本文
着重研究该模型在单个行业内的预测能力。

通过估计已实现协方差矩阵的方式来度量多个资产价格变化的波动率。构建已实现协方差矩
阵，当所选取的数据足够高频时，已实现协方差矩阵趋近于二次幂协方差矩阵。高频容易出
现噪音干扰，价格存在失真，使用两种不同的降噪方法对已实现协方差矩阵进行估计，选择
效果最好的。

根据已建立的资产对数收益率序列和估计出的 已实现协方差模型来建立预测模型。

**实证分析**

**数据：**为保证拟合效果，选取2017年波动最为剧烈的板块之一：银行板块。同时根据
Barndorff-Nielsen 等(2009)提供的预处理方法中对交易数据源于同一交易所 交易的要
求，选取WIND行业中心中银行板块下，规模前 10的在上证交易所上市的公司，并从预测者
网站上购买 得到这些公司的**逐笔交易**数据（由于浦发银行中间一段时 间停牌，因此除
去其后选取原规模排名11位的光大银行补上）。本文采用 的是“收盘价-开盘价”收益率。选
取所有个股在2016年1月4日至2018年3月 26日间的交易数据。筛选出**10只股票共同发生交
易的交易日**，同时剔除出一些极端天数后，得到541天的逐笔交 易数据。同时，将数据分
成两组：第一组作为样本内数据，用于 拟合静态参数；第二组作为样本外数据，用于对比
以检验 模型预测效果。

在韩清等（2009）[@韩清2009]的研究中已经指出，我国微观市场结构导致的噪声较美股更
大，所以国外文献中常使用5分钟间隔抽样在我国并不适用。

**结论**从模型的预测效果上看，对于银行业而言，模型的预测效果明显优于传统模型，能
准确地预测银行间的波动率 以及波动率之间的关联程度。同时，这个结果不仅限于银 行
业，还可类推至别的行业。与银行业相似，模型在别的 行业应用时，预测能力同样很强，
对于预测同一行业内各只股票的波动率以及他们之间的关联性具有较强实用价值。（能源行
业，保险行业等）

## implied, realized, and GARCH 波动率预测的比较
1. An international comparison of implied, realized, and GARCH volatility
   forecasts [@Kourtis2016]

**题目：**隐含，已实现和GARCH波动率预测的国际比较(2016)

**摘要：**我们比较了来自10个国家的13个股票指数的隐含波动率、已实现波动率和GARCH
波动率模型的预测能力和经济价值。不同国家的模型排名相似，但随着预测范围的变化而变
化。在每日水平上，异质自回归模型提供了最准确的预测，而修正波动风险溢价的隐含波动
模型在每月水平上更优越。在几乎所有考虑的情况下，广泛使用的GARCH模型的性能都较
差。在2008-2009年危机期间，所有方法的表现都非常糟糕。最后，**隐含波动率相对于国
际投资组合多样化的历史方法提供了显著的改进**。

**数据：**从Bloomberg收集了13个国际股票指数的每日股息调整收盘水平。我们用这些来
计算百分比指数回报率。其次，我们对每一个股票指数使用一个每日已实现的波动率序列，
由等间距的5分钟日内收益率构成。从Bloomberg获得了与所考虑的股票市场相对应的期权隐
含波动率指数的每日数据。使用的所有隐含波动率指数都是以无模型方式构建的。我们的样
本涵盖了从2000年1月3日到2012年10月26日的时间段，尽管对于某些市场来说样本较短。



2. Forecasting stock return volatility: a comparison of GARCH, Implied
   volatility, and realized volatility models [@Kambouroudis2016]

**题目：**预测股票收益波动率：GARCH，隐含波动率和已实现波动率模型的比较（2016）





# 研究思路
## 已实现的Wishart-GARCH
1. 模型实证意义：Realized Wishart-GARCH 2016年才提出来[@Hansen2016a]，可预测股市
   中某个行业的波动率与其他模型进行比较。
2. 创新型：做的人不多，中文期刊只有2019年发表的针对银行业波动率的预测[@周少甫2019],可以选择另一个行业进行预测
3. 数据可获得性：股市交易数据较易获取
4. R包已找到，关于RCC包（http://www.mamicode.com/info-detail-1468193.html ）
   
## 题目
1. 得分驱动的已实现Wishart-GARCH模型及应用——多元资产波动率预测（定位与跨公司和跨行业）

2. 基于Realized Wishart-GARCH对波动率预测研究——以原油市场为例（定位于某个行业）


## 模型
以realized Wishart-GARCH模型(得分驱动的多元资产波动模型)为主
### 相关模型
realized garch 模型、已实现的SV模型、多元的realized garch 模型，多元realized
Wishart-GARCH模型比较,与BEKK,EWMA进行预测效果对比。

## 数据
### 数据来源

### 数据处理
1. 数据逐笔清理
2. 刷新时间抽样
3. 
### 

# 参考文献
[//]: # (\bibliography{Bibfile})